### ISSUE TITLE
Missing pandas import in Folum Notebook

### ISSUE THREAD

**Issue by pkienscherf3** [IS3UniCologne/PDS_Code#2]
Description: 
When I am running the Folium notebook, I get an error that pandas has not been imported.

Steps to reproduce:
Run the cells ...

Tasks
Import pandas before it is needed.

**Comment by pkienscherf** [comment]
Already addressed with #0e84f376f594c91baf01854cca89fed5c98b4a69

**Comment by pkienscherf** [comment]
Already addressed with commit 0e84f376f594c91baf01854cca89fed5c98b4a69
